In [8]:
import pandas as pd
import numpy as np

In [9]:
data1=pd.read_csv("Dataset.csv")
data1.head()

Unnamed: 0  age  weight(kg)  height(m) gender        BMI      BMR  \
0           1    2   16.097862   0.932025      F  18.531612  958.584   
1           2    4   14.619374   0.916687      F  17.397496  932.383   
2           4    4   17.899918   0.997288      F  17.997414  977.578   
3           6    3   13.532880   1.022786      F  12.936609  944.689   
4           8    4   17.039484   1.053977      M  15.338909  799.229   

   activity_level  calories_to_maintain_weight  BMI_tags  Label  
0             1.2                    1150.3008         8     13  
1             1.7                    1585.0511         7      1  
2             1.9                    1857.3982         7      4  
3             1.9                    1794.9091         7      3  
4             1.9                    1518.5351         7      0

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10726 entries, 0 to 10725
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Unnamed: 0                   10726 non-null  int64  
 1   age                          10726 non-null  int64  
 2   weight(kg)                   10726 non-null  float64
 3   height(m)                    10726 non-null  float64
 4   gender                       10726 non-null  object 
 5   BMI                          10726 non-null  float64
 6   BMR                          10726 non-null  float64
 7   activity_level               10726 non-null  float64
 8   calories_to_maintain_weight  10726 non-null  float64
 9   BMI_tags                     10726 non-null  int64  
 10  Label                        10726 non-null  int64  
 11  cluster                      10726 non-null  int64  
 12  gender_encoded               10726 non-null  int64  
dtypes: float64(6), i

Creating Encoded column to gender

In [12]:
gender_category = data1["gender"]

In [13]:
from sklearn.preprocessing import LabelEncoder
obj = LabelEncoder()
colum_gender = obj.fit_transform(gender_category)
colum_gender

array([0, 0, 0, ..., 0, 0, 1])

Adding encoded gender column to csv file

In [14]:
obj = LabelEncoder()
column_gender = obj.fit_transform(data1['gender'])

# Add the encoded gender column to the DataFrame
data1['gender_encoded'] = column_gender

# Save the updated DataFrame to a new CSV file
data1.to_csv('Updated_adding_gender.csv', index=False)

In [15]:
data2=pd.read_csv("Updated_adding_gender.csv")
data2.head()

Unnamed: 0  age  weight(kg)  height(m) gender        BMI      BMR  \
0           1    2   16.097862   0.932025      F  18.531612  958.584   
1           2    4   14.619374   0.916687      F  17.397496  932.383   
2           4    4   17.899918   0.997288      F  17.997414  977.578   
3           6    3   13.532880   1.022786      F  12.936609  944.689   
4           8    4   17.039484   1.053977      M  15.338909  799.229   

   activity_level  calories_to_maintain_weight  BMI_tags  Label  \
0             1.2                    1150.3008         8     13   
1             1.7                    1585.0511         7      1   
2             1.9                    1857.3982         7      4   
3             1.9                    1794.9091         7      3   
4             1.9                    1518.5351         7      0   

   gender_encoded  
0               0  
1               0  
2               0  
3               0  
4               1

Removing outliers and saving to a new csv file

In [16]:
from scipy import stats

In [17]:
# Define a threshold for the Z-score
z_threshold = 3

# Calculate the Z-scores for the 'BMI' column
z_scores = stats.zscore(data['BMI'])

# Identify outliers based on the Z-scores
outliers = (z_scores > z_threshold) | (z_scores < -z_threshold)

# Remove outliers from the DataFrame
df_no_outliers = data[~outliers]

# Save the DataFrame without outliers to a new CSV file
df_no_outliers.to_csv('Updated_no_outliers.csv', index=False)

In [18]:
data=pd.read_csv("Updated_no_outliers.csv")
data.head()

Unnamed: 0  age  weight(kg)  height(m) gender        BMI      BMR  \
0           1    2   16.097862   0.932025      F  18.531612  958.584   
1           2    4   14.619374   0.916687      F  17.397496  932.383   
2           4    4   17.899918   0.997288      F  17.997414  977.578   
3           6    3   13.532880   1.022786      F  12.936609  944.689   
4           8    4   17.039484   1.053977      M  15.338909  799.229   

   activity_level  calories_to_maintain_weight  BMI_tags  Label  cluster  \
0             1.2                    1150.3008         8     13        2   
1             1.7                    1585.0511         7      1        2   
2             1.9                    1857.3982         7      4        2   
3             1.9                    1794.9091         7      3        2   
4             1.9                    1518.5351         7      0        2   

   gender_encoded  
0               0  
1               0  
2               0  
3               0  
4               1

In [29]:
data.describe()

Unnamed: 0           age    weight(kg)     height(m)           BMI  \
count  10726.000000  10726.000000  10726.000000  10726.000000  10726.000000   
mean   11664.753123     26.778575     61.647728      1.540276     24.788317   
std     6814.683196     18.201675     24.254566      0.186042      6.954637   
min        1.000000      2.000000     12.005536      0.856328     10.342285   
25%     5959.750000     13.000000     45.538375      1.564845     19.557137   
50%    10695.500000     23.000000     61.323460      1.631282     23.056039   
75%    17455.250000     36.000000     83.484585      1.632234     31.334294   
max    23998.000000     90.000000     98.799820      1.633223     37.142927   

                BMR  activity_level  calories_to_maintain_weight  \
count  10726.000000    10726.000000                 10726.000000   
mean    1442.049923        1.487451                  2118.574075   
std      250.686166        0.239625                   388.425427   
min      667.941000        1.200000                   953.540900   
25%     1320.322500        1.300000                  1815.879700   
50%     1493.165000        1.500000                  2104.599800   
75%     1602.488000        1.700000                  2405.301750   
max     1914.374000        1.900000                  2949.075500   

           BMI_tags         Label       cluster  gender_encoded  
count  10726.000000  10726.000000  10726.000000    10726.000000  
mean       8.253496     19.332650      0.659705        0.480515  
std        0.754767      9.746498      0.719617        0.499643  
min        7.000000      0.000000      0.000000        0.000000  
25%        8.000000     16.000000      0.000000        0.000000  
50%        8.000000     20.000000      1.000000        0.000000  
75%        9.000000     28.000000      1.000000        1.000000  
max        9.000000     31.000000      2.000000        1.000000

Initializing X for model

In [42]:
x = data.iloc[:,[0,1,-1,2,3,6,7]]
x.head()

Unnamed: 0  age  gender_encoded  weight(kg)  height(m)      BMR  \
0           1    2               0   16.097862   0.932025  958.584   
1           2    4               0   14.619374   0.916687  932.383   
2           4    4               0   17.899918   0.997288  977.578   
3           6    3               0   13.532880   1.022786  944.689   
4           8    4               1   17.039484   1.053977  799.229   

   activity_level  
0             1.2  
1             1.7  
2             1.9  
3             1.9  
4             1.9

Initializing Y for model

In [31]:
y = data.iloc[:,-5]
y.head()

0    1150.3008
1    1585.0511
2    1857.3982
3    1794.9091
4    1518.5351
Name: calories_to_maintain_weight, dtype: float64

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [43]:
x = scaler.fit_transform(x)
x[0:4]

array([[-1.71164184, -1.36139833, -0.96175987, -1.87807891, -3.26957998,
        -1.92866032, -1.1996431 ],
       [-1.71149509, -1.25151321, -0.96175987, -1.93903886, -3.35202752,
        -2.03318233,  0.88704798],
       [-1.71120159, -1.25151321, -0.96175987, -1.80377784, -2.91876741,
        -1.85288875,  1.72172441],
       [-1.71090809, -1.30645577, -0.96175987, -1.98383637, -2.78170284,
        -1.98409077,  1.72172441]])

Splitting Dataset to trainset and testing set

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

In [39]:
x_train.shape

(8044, 8)

Training Random forest model for predict "Calories to maintain weight"

In [50]:
from sklearn.ensemble import RandomForestRegressor
# Create a Random Forest Regressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
predictions = model.predict(x_test)

Mean squared error

In [51]:
from sklearn.metrics import mean_squared_error

# Assuming predictions is your predicted values for the test set
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 10.164520930593067


Checking predicted values and original values

In [52]:
predict = model.predict(x_test)
predict[0:10]

array([2138.6787  , 2766.997303, 1811.693793, 2801.406588, 1656.633578,
       1833.2652  , 2641.493715, 2752.25886 , 2763.585929, 1998.852063])

In [53]:
y_test[0:10]

8570    2138.7888
3031    2767.1467
4245    1811.6384
3592    2801.3068
895     1656.6381
5753    1833.2041
4110    2641.2451
9139    2752.2337
6684    2763.8274
3871    1998.8319
Name: calories_to_maintain_weight, dtype: float64